/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cwRBEVlAlLS
 */
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { JSX, SVGProps } from "react";

export function Tiers() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 p-4 md:p-6">
      <Card className="bg-green-100 dark:bg-green-900">
        <CardHeader>
          <CardTitle>S Tier</CardTitle>
        </CardHeader>
        <CardContent className="flex items-center space-x-4">
          <ShieldIcon className="w-6 h-6" />
          <div>
            <h3 className="font-bold">Reinhardt</h3>
            <p className="text-sm text-gray-500">Tank</p>
          </div>
        </CardContent>
      </Card>
      <Card className="bg-blue-100 dark:bg-blue-900">
        <CardHeader>
          <CardTitle>A Tier</CardTitle>
        </CardHeader>
        <CardContent className="flex items-center space-x-4">
          <CrosshairIcon className="w-6 h-6" />
          <div>
            <h3 className="font-bold">McCree</h3>
            <p className="text-sm text-gray-500">Damage</p>
          </div>
        </CardContent>
      </Card>
      <Card className="bg-yellow-100 dark:bg-yellow-900">
        <CardHeader>
          <CardTitle>B Tier</CardTitle>
        </CardHeader>
        <CardContent className="flex items-center space-x-4">
          <HelpingHandIcon className="w-6 h-6" />
          <div>
            <h3 className="font-bold">Mercy</h3>
            <p className="text-sm text-gray-500">Support</p>
          </div>
        </CardContent>
      </Card>
      <Card className="bg-orange-100 dark:bg-orange-900">
        <CardHeader>
          <CardTitle>C Tier</CardTitle>
        </CardHeader>
        <CardContent className="flex items-center space-x-4">
          <BombIcon className="w-6 h-6" />
          <div>
            <h3 className="font-bold">Junkrat</h3>
            <p className="text-sm text-gray-500">Damage</p>
          </div>
        </CardContent>
      </Card>
      <Card className="bg-red-100 dark:bg-red-900">
        <CardHeader>
          <CardTitle>D Tier</CardTitle>
        </CardHeader>
        <CardContent className="flex items-center space-x-4">
          <ShieldIcon className="w-6 h-6" />
          <div>
            <h3 className="font-bold">Orisa</h3>
            <p className="text-sm text-gray-500">Tank</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function ShieldIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10" />
    </svg>
  );
}

function CrosshairIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <line x1="22" x2="18" y1="12" y2="12" />
      <line x1="6" x2="2" y1="12" y2="12" />
      <line x1="12" x2="12" y1="6" y2="2" />
      <line x1="12" x2="12" y1="22" y2="18" />
    </svg>
  );
}

function HelpingHandIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 15 5.12-5.12A3 3 0 1 10.24 9H13a2 2 4h-2.5m4-.68 4.17-4.89a1.88 1.88 2.92 2.36l-4.2 5.94A3 14.96 17H9.83a2 0-1.42.59L7 19" />
      <path d="m2 14 6" />
    </svg>
  );
}

function BombIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="13" r="9" />
      <path d="m19.5 9.5 1.8-1.8a2.4 2.4 0 0-3.4l-1.6-1.6a2.41 2.41 0-3.4 0l-1.8 1.8" />
      <path d="m22 2-1.5 1.5" />
    </svg>
  );
}
